---
- name: Update apt
  apt:
    update_cache: yes
- name: Ensure php5 fpm + libs is installed
  apt:
    pkg: "{{item}}"
    state: latest
  with_items:
   - php5-fpm
   - php5-mysqlnd
   - php5-curl
   - php5-gd
   - php5-pgsql
- name: Install Nginx conf for PHP-FPM
  copy:
    src: php-fpm.nginx.conf
    dest: /etc/nginx/php-fpm.conf
  notify:
  - Restart Nginx
- name: Writes the correct version of the ini configuration
  copy:
    src: php.ini
    dest: /etc/php5/fpm/php.ini
- name: Writes the correct version of the configuration
  copy:
    src: php-fpm.conf
    dest: /etc/php5/fpm/php-fpm.conf
- name: Ensure the log folder is here
  file:
    path: /var/log/php-fpm
    state: directory
    owner: root
    group: root
- name: Writes the correct version of the pool
  copy:
    src: www.conf
    dest: /etc/php5/fpm/pool.d/www.conf
  notify:
  - Restart PHP FPM