---
- name: Install ftp
  apt: 
    name: ftp
    state: latest
- name: Create the backup directory.
  file:
    state: directory
    path: "/home/{{user}}/backup/"
    owner: "{{user}}"
    group: www-data
    mode: 0755
- name: Copy the backup script
  copy:
    src: backup.sh
    dest: "/home/{{user}}/backup/backup.sh"
    owner: tchap
    group: www-data
    mode: 0755
- name: Copy the .netrc conf file
  copy:
    dest: "/home/{{user}}/.netrc"
    owner: tchap
    mode: 0600 # needed since it contains a password
    content: |
        machine {{ ftp_server }}
            login {{ ftp_login }}
            password {{ ftp_password }}
  become: yes
- name: Ensure the base directory is written in the conf
  lineinfile:
    dest: "/home/{{user}}/backup/backup.sh"
    insertafter: "# Home root directory"
    line: "HOME_DIR='/home/{{user}}'"
- name: Ensure the backup password is written in the conf
  lineinfile:
    dest: "/home/{{user}}/backup/backup.sh"
    insertafter: "MYSQL_USER='backup'"
    line: "MYSQL_PASSWORD='{{ lookup('file', '/tmp/ansible.password.mysql_backup_' + inventory_hostname) }}'"
- name: Add the cron task for backups
  cron:
    user: "{{user}}"
    name: "Backup"
    hour: "03"
    minute: "42"
    job: "/home/{{user}}/backup/backup.sh"
