---
  - name: Ensure the key is present
    apt_key:
      url: https://packages.elastic.co/GPG-KEY-elasticsearch
  - name: Add repository
    copy:
      src: kibana.list
      dest: "/etc/apt/sources.list.d/kibana.list"
    notify:
    - Update apt
  - name: Ensure kibana is installed
    apt:
      pkg: kibana
      state: latest
  - name: Ensure kibana is reloaded
    service: 
      name: kibana
      state: restarted
  - name: Ensure kibana starts at boot
    service: 
      name: kibana
      enabled: yes
  - name: Write kibana.yml 
    copy:
      src: kibana.yml
      dest: "/opt/kibana/config/kibana.yml"
  - name: Ensure kibana nginx conf is here
    copy:
      src: kibana4.conf
      dest: /etc/nginx/available/kibana4.conf
  # - name: Copy Web dashboard
  #   copy:
  #     src: web.json
  #     dest: "/home/{{user}}/kibana/app/dashboards/web.json"
  # - name: Copy Systems dashboard
  #   copy:
  #     src: systems.json
  #     dest: "/home/{{user}}/kibana/app/dashboards/systems.json"
  # - name: Copy Energy dashboard
  #   copy:
  #     src: energy.json
  #     dest: "/home/{{user}}/kibana/app/dashboards/energy.json"
  - name: Write server_name
    lineinfile:
      dest: /etc/nginx/available/kibana4.conf
      state: present
      regexp: '  server_name           '
      line: "  server_name           {{ monitoring_server }};"
  - name: Ensure kibana4 nginx conf is enabled
    shell: "ln -fs /etc/nginx/available/kibana4.conf /etc/nginx/enabled/kibana4.conf"
  - name: Ensure python-passlib is installed
    apt:
      name: python-passlib
      state: present
  - name: Create htpasswd
    htpasswd:
      path: /etc/nginx/available/kibana.htpasswd
      name: "{{ user }}"
      password: "{{ htpasswd }}"
      owner: root
      group: www-data
      mode: 0640