---
- name: Ensure php7 jessie GPG key is present
  apt_key:
    url: https://www.dotdeb.org/dotdeb.gpg
- name: Add repository
  apt_repository:
    repo: 'deb http://packages.dotdeb.org {{ ansible_distribution_release }} all'
    state: present
  notify:
  - Update apt
- name: Ensure php7 cli and php7-mysql is installed
  apt:
    pkg: "{{item}}"
    state: latest
  with_items:
   - php7.0
   - php7.0-cli
   - php7.0-mysql
- name: Add correct timezone
  lineinfile:
    dest: /etc/php/7.0/cli/php.ini
    line: 'date.timezone = "Europe/Paris"'
    state: present
    insertafter: "^[Date]"
