---
- name: Ensure the key is present
  apt_key:
    url: https://packages.elastic.co/GPG-KEY-elasticsearch
  - name: Add repository
    copy:
      src: elk.list
      dest: "/etc/apt/sources.list.d/elk.list"
    notify:
    - Update apt
- name: Ensure java is installed
  apt:
    pkg: elasticsearch
    state: latest
- name: Ensure elasticsearch is installed
  apt:
    pkg: openjdk-7-jre-headless
    state: latest
- name: Copy elasticsearch configuration
  copy:
    src: elasticsearch.yml
    dest: /etc/elasticsearch/elasticsearch.yml
- name: Copy elasticsearch nginx proxy configuration
  copy:
    src: elasticsearch.proxy.conf
    dest: /etc/nginx/available/elasticsearch.proxy.conf
- name: Ensure the host is correctly written in the conf
  lineinfile:
    dest: /etc/nginx/available/elasticsearch.proxy.conf
    insertafter: "  listen 8080;"
    line: "  server_name  {{ monitoring_server }};"
- name: Remove htpasswd file
  file:
    path: /etc/elasticsearch/elasticsearch.htpasswd
    state: absent
- name: Create htpasswd for elasticsearch
  htpasswd:
    path: /etc/elasticsearch/elasticsearch.htpasswd
    name: "{{ user }}"
    password: "{{ lookup('password', '/tmp/ansible.password.elasticsearch_proxy length=64') }}"
    owner: root
    group: www-data
    mode: 0640
  notify:
    - Restart Nginx
- name: Link Nginx proxy conf
  file:
    src: /etc/nginx/available/elasticsearch.proxy.conf
    dest: /etc/nginx/enabled/elasticsearch.proxy.conf
    state: links
- name: Start elasticsearch
  service:
    name: elasticsearch
    state: restarted
    enabled: yes
